// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmRWiMEr9skJEH_0MyqljP3BCULshAUDQ',
    appId: '1:673988906375:web:9b189c70b96ac901735722',
    messagingSenderId: '673988906375',
    projectId: 'todoapp-8b403',
    authDomain: 'todoapp-8b403.firebaseapp.com',
    storageBucket: 'todoapp-8b403.firebasestorage.app',
    measurementId: 'G-3MLVZC3KJ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCc9IBC7BRoGBAS8aDF_bQRk1XSk0Y_qhw',
    appId: '1:673988906375:android:a0f75b6a5071dd81735722',
    messagingSenderId: '673988906375',
    projectId: 'todoapp-8b403',
    storageBucket: 'todoapp-8b403.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA37HCuCyJKaYYPcGgoUX_-JB2RGg1vQyM',
    appId: '1:673988906375:ios:c65d8e3163bbaaeb735722',
    messagingSenderId: '673988906375',
    projectId: 'todoapp-8b403',
    storageBucket: 'todoapp-8b403.firebasestorage.app',
    iosBundleId: 'com.example.toDoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA37HCuCyJKaYYPcGgoUX_-JB2RGg1vQyM',
    appId: '1:673988906375:ios:c65d8e3163bbaaeb735722',
    messagingSenderId: '673988906375',
    projectId: 'todoapp-8b403',
    storageBucket: 'todoapp-8b403.firebasestorage.app',
    iosBundleId: 'com.example.toDoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmRWiMEr9skJEH_0MyqljP3BCULshAUDQ',
    appId: '1:673988906375:web:8febe6605174a3e3735722',
    messagingSenderId: '673988906375',
    projectId: 'todoapp-8b403',
    authDomain: 'todoapp-8b403.firebaseapp.com',
    storageBucket: 'todoapp-8b403.firebasestorage.app',
    measurementId: 'G-X56VF5SN3X',
  );
}
